In [1]:
import numpy as np

In [21]:
class BlockSize(object):
    def __init__(self, x = 32, y = 32):
        self.x = 32
        self.y = 32

blockSize = BlockSize(64, 16)
memoryIdx = []
for thready in range(16):
    for threadx in range(64):
        i = threadx 
        j = thready * 4
        this_thread = []
        for k in range (j, j+4):
            idx = k + i
            this_thread.append(idx)
        memoryIdx.append(this_thread)
print(len(memoryIdx))
print(memoryIdx)

1024
[[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14], [12, 13, 14, 15], [13, 14, 15, 16], [14, 15, 16, 17], [15, 16, 17, 18], [16, 17, 18, 19], [17, 18, 19, 20], [18, 19, 20, 21], [19, 20, 21, 22], [20, 21, 22, 23], [21, 22, 23, 24], [22, 23, 24, 25], [23, 24, 25, 26], [24, 25, 26, 27], [25, 26, 27, 28], [26, 27, 28, 29], [27, 28, 29, 30], [28, 29, 30, 31], [29, 30, 31, 32], [30, 31, 32, 33], [31, 32, 33, 34], [32, 33, 34, 35], [33, 34, 35, 36], [34, 35, 36, 37], [35, 36, 37, 38], [36, 37, 38, 39], [37, 38, 39, 40], [38, 39, 40, 41], [39, 40, 41, 42], [40, 41, 42, 43], [41, 42, 43, 44], [42, 43, 44, 45], [43, 44, 45, 46], [44, 45, 46, 47], [45, 46, 47, 48], [46, 47, 48, 49], [47, 48, 49, 50], [48, 49, 50, 51], [49, 50, 51, 52], [50, 51, 52, 53], [51, 52, 53, 54], [52, 53, 54, 55], [53, 54, 55, 56], [54, 55, 56, 57], [55, 56, 57, 58], [56, 57, 58, 59], [5

In [ ]:
for i in range(4):
    for j in range(4):
        

In [28]:
x1mat = np.asarray([[0, 0, 0, 1],
                    [0, 0, 1, 1],
                    [0, 1, 0, 1],
                    [1, 0, 0, 1],
                   [0, 1, 1, 1],
                   [1, 1, 0, 1],
                   [1., 0, 1, 1],
                   [1, 1, 1, 1]])

# x1mat = np.asarray([[0.5, 0., 0.5, 1],
#                   [-0.5, 0, 0.5, 1],
#                   [0., 0., -1, 1],
#                   [0, -2, 0, 1]])

x1mat_t = np.transpose(x1mat)
y = np.matmul(x1mat_t, x1mat)
print(y)
    

[[4. 2. 2. 4.]
 [2. 4. 2. 4.]
 [2. 2. 4. 4.]
 [4. 4. 4. 8.]]


In [34]:
xx4x4 = np.asarray([[0.5, 0, 0, 0],
                   [0.0, 4, 0, -2],
                   [0, 0, 1.5, 0],
                   [0, -2, 0, 4]])

M = np.asarray([[1, 0, 0, 0],
               [0, 0.73169, -0.681639, 0],
               [0, 0.68164, 0.731689, 0],
               [0, 0, 0, 1]])

y = np.matmul(xx4x4, np.transpose(M))
print(y)

[[ 0.5        0.         0.         0.       ]
 [ 0.         2.92676    2.72656   -2.       ]
 [ 0.        -1.0224585  1.0975335  0.       ]
 [ 0.        -1.46338   -1.36328    4.       ]]


In [36]:
M = np.asarray([[2, 0, 0, 0],
                [0, 2, 0, 0],
                [0, 2.22045e-15, 2, 0],
                [0, -4.47035e-08, -3.97364e-08, 1]])
A = np.asarray([[0, 0,0, 1],
               [0, 0, 1, 1],
               [0, 1, 0, 0],
               [1, 0, 0, 1],
               [0, 1, 1, 1],
               [1, 1, 0, 1],
               [1, 0, 1, 1],
               [1, 1, 1, 1]])

y = np.matmul(M, np.transpose(A))
print(np.transpose(y))

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e+00  9.99999960e-01]
 [ 0.00000000e+00  2.00000000e+00  2.22045000e-15 -4.47035000e-08]
 [ 2.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  2.00000000e+00  2.00000000e+00  9.99999916e-01]
 [ 2.00000000e+00  2.00000000e+00  2.22045000e-15  9.99999955e-01]
 [ 2.00000000e+00  0.00000000e+00  2.00000000e+00  9.99999960e-01]
 [ 2.00000000e+00  2.00000000e+00  2.00000000e+00  9.99999916e-01]]
